GET http://localhost:2000/posts
phone_number: +250784824295

###
POST http://localhost:2000/signup
Accept: application/json
Content-Type: application/json

{
    "password" : "kamunikwi",
    "phone_number":"250784824295",
    "name":"Christophe K. Kwizera"
}
###
POST http://localhost:2000/login
Accept: application/json
Content-Type: application/json

{
    "password" : "kamunikwi",
    "phone_number":"250784824295"
}
###
POST http://localhost:2000/getinfo
Accept: application/json
Content-Type: application/json

{
    "password" : "kamunikwi",
    "phone_number":"250784824295",
    "name":"Christophe K. Kwizera"
}